### ISSUE TITLE
ツイートを手動削除するとマイページの表示に失敗する

### ISSUE THREAD

**Issue by Lycheejam** [Lycheejam/twe-todo-app#27]
タスク登録後にtodoアプリからツイートされたツイートを削除すると
mypageを表示した際にtweetのembedを取得できずエラーとなる。

```
An unhandled exception occurred while processing the request.
WebException: The remote server returned an error: (404) Not Found.
System.Net.HttpWebRequest.GetResponse()

TwitterException: Sorry, that page does not exist
twe_todo_app.Models.TodoManager.TwitterClient.GetEmbed(long tweetId) in TwitterClient.cs, line 80

Stack Query Cookies Headers
WebException: The remote server returned an error: (404) Not Found.
System.Net.HttpWebRequest.GetResponse()
CoreTweet.Request.HttpNoBody(MethodType type, Uri url, string authorizationHeader, ConnectionOptions options)
CoreTweet.Core.TokensBase.SendRequestImpl(MethodType type, string url, IEnumerable<KeyValuePair<string, object>> parameters, ConnectionOptions options)

Show raw exception details
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at CoreTweet.Request.HttpNoBody(MethodType type, Uri url, String authorizationHeader, ConnectionOptions options)
   at CoreTweet.Core.TokensBase.SendRequestImpl(MethodType type, String url, IEnumerable`1 parameters, ConnectionOptions options)
TwitterException: Sorry, that page does not exist
twe_todo_app.Models.TodoManager.TwitterClient.GetEmbed(long tweetId) in TwitterClient.cs
-
        public async Task<Embed> GetEmbed(long tweetId) {
            try {
                var tokens = await CreateTokens();
                var emb = tokens.Statuses.Oembed(tweetId);
                return emb;
            } catch (Exception e) {
                throw e;
            }
        }
        /// <summary>
        /// Creates the tokens.
        /// Twitter api認証用トークン作成処理
twe_todo_app.Controllers.TodoController.MyPage() in TodoController.cs
-
                //ログイン中 かつ タスクが存在しない場合
                return View();
            }
            //取得成否の判定が必要 ここのエラー処理どうしよう？
            //ツイート取得
            var emb = await _twitterclient.GetEmbed(resTodo.TweetId);
            //ログイン中 かつ タスクが存在した場合の表示
            return View(emb);
        }
        /// <summary>
        /// Regist this instance.
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
CoreTweet.TwitterException: Sorry, that page does not exist ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at CoreTweet.Request.HttpNoBody(MethodType type, Uri url, String authorizationHeader, ConnectionOptions options)
   at CoreTweet.Core.TokensBase.SendRequestImpl(MethodType type, String url, IEnumerable`1 parameters, ConnectionOptions options)
   --- End of inner exception stack trace ---
   at twe_todo_app.Models.TodoManager.TwitterClient.GetEmbed(Int64 tweetId) in /Users/z/Projects/twe-todo-app/twe-todo-app/Models/TodoManager/TwitterClient.cs:line 80
   at twe_todo_app.Controllers.TodoController.MyPage() in /Users/z/Projects/twe-todo-app/twe-todo-app/Controllers/TodoController.cs:line 83
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Lycheejam** [comment]
fix d25cb7de08ccf1a75798e7473883607ed6ffd6ee
TwitterExceptionが404 errorの場合、embed無しのmypage表示に遷移するよう修正した。
